version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: user_management_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: user_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./BUILD_DATABASE.SQL:/docker-entrypoint-initdb.d/BUILD_DATABASE.SQL

volumes:
  db_data: